### ISSUE TITLE
[Feature Request] ability to smelt ingots, blocks, tools & armor

### ISSUE THREAD

**Issue by Balakay420** [sussy-syrup/smithees-foundry#18]
outputs should be equivalent to the amount of materials it takes to craft

OR

based off of durability

**Comment by sussy-syrup** [comment]
all ingots and blocks are smeltable I believe. For tools and armour I am thinking of doing at most 1 ingot to prevent the smeltery being used as an uncrafting method

**Comment by Balakay420** [comment]
I'd double check the block and ingots, I tried doing last night &  it didn't work. I'm not home right now or id check again myself

**Comment by sussy-syrup** [comment]
I will look into it. Might be one of those rare bugs that only exist outside the dev environment

**Comment by sussy-syrup** [comment]
![2022-07-30_23 34 38](https://user-images.githubusercontent.com/96626528/182002631-960c83a1-8fe0-4419-af53-ac1585e52aed.png)
![2022-07-30_23 48 02](https://user-images.githubusercontent.com/96626528/182002662-745d6775-cfe2-4231-86fc-564e21287341.png)

The first is dev and the second is release. Both seem to be working in the latest version. Perhaps you tried it with a different mod or with the corroded copper blocks (if I did not add them to the tags) ?

**Comment by Balakay420** [comment]
ah i was just impatient when I tried blocks, they take awhile. they're both working on my end. 

Also it might just be me, but the smelting progression bar would look better on the left side in my opinion.

**Comment by Balakay420** [comment]
As for the smelting tools and armor, yeah that makes sense. Parts would also make sense to add, however those should be the amount it takes to cast logically

**Comment by sussy-syrup** [comment]
Reworking the gui will not be a priority at the moment. Parts are already supported unless something broke with that recently
