### ISSUE TITLE
Crash with REI when starting server [Fabric]

### ISSUE THREAD

**Issue by sirben99** [sussy-syrup/smithees-foundry#19]
Hey!

I seem to have a crash when starting the server whenever i added this mod. It dint generate a crash report but it shows at the bottom of the log.

Mod Loader: Fabric
Mod version: smithees-foundry-1.3.2

Log:
[logs_latest (1).log](https://github.com/sussy-syrup/smithees-foundry/files/9227054/logs_latest.1.log)

If you need anything else please let me know!

Ben

**Comment by sussy-syrup** [comment]
my bad, that's from a left-over entrypoint that I ended up not using and deleting

**Comment by sirben99** [comment]
Np! Im glad you managed to pinpoint the issue!

**Comment by sussy-syrup** [comment]
uploading now

**Comment by sirben99** [comment]
Hey, just wanted to let you know that everything worked out great! No crashes etc. Thank you for the quick fix and keep up the good work, looking forward for more updates!
