### ISSUE TITLE
Rendering Issues When Using Sodium

### ISSUE THREAD

**Issue by IceArrow04** [sussy-syrup/smithees-foundry#2]
When playing while running Sodium rendering for all the finished tools is broken and they display as nothing when held. Textures for the part benches are also broken causing missing texture placeholders.

![2022-07-12_21 09 48](https://user-images.githubusercontent.com/48144917/178650989-d3cad2ee-029a-4ec7-b4f6-ae82d13dd216.png)
![2022-07-12_21 09 30](https://user-images.githubusercontent.com/48144917/178650980-df9e125e-8b02-4a46-a5cb-7bbee6909257.png)

### Mods Used
Architectury-4.4.56
Cloth Config-6.2.62-Fabric
Fabric API-0.57.0+1.18.2
Patchouli-1.18.2-71.1-Fabric
Roughly Enough Items-8.1.457
Sodium-Fabric-mc1.18.2-0.4.1+build.15
The-Forge-1.2.0

**Comment by sussy-syrup** [comment]
Sodium does not support the Fabric Rendering API which is used for those blocks and items. I will see what I can do but it won't be something I will prioritise fixing. 

For now I must recommend Indium which is an addon for sodium which adds Fabric API support. Here is a link:
https://www.curseforge.com/minecraft/mc-mods/indium
