### ISSUE TITLE
Warning: Tried to load a block entity for block Block{minecraft:smithing_table} but failed

### ISSUE THREAD

**Issue by Steveplays28** [sussy-syrup/smithees-foundry#26]
```
[16:12:44] [Server thread/WARN]: Tried to load a block entity for block Block{minecraft:smithing_table} but failed at location class_2338{x=114, y=43, z=224}
[16:12:44] [Server thread/WARN]: Block entities size mismatch! expected 1 but got 0
```
Not sure why this warning was triggered, but it triggered when I was playing around with Smithee's Foundry. Not an error, but thought I'd report it anyway

Thank you for this awesome mod by the way! Awesome that you made it generate parts from modded resources as well.

**Comment by sussy-syrup** [comment]
Thank you for the report. If there are any issues with that block or it happens each time please let me know. Otherwise it's probably minecraft not doing something correctly with block entities as the mod creates block entities using vanilla methods

**Comment by sussy-syrup** [comment]
thank you! I will be closing the issue for now
