### ISSUE TITLE
Smeltery GUI Causes Cursor Snapping

### ISSUE THREAD

**Issue by IceArrow04** [sussy-syrup/smithees-foundry#3]
Switching tabs while in the smeltery GUI causes the mouse cursor to snap back to the center of the screen every time you switch tabs.

https://user-images.githubusercontent.com/48144917/178653203-4eba67f4-a4c9-426f-8a25-0e0da22ddfd8.mp4

### Mods Used
Architectury-4.4.56
Cloth Config-6.2.62-Fabric
Fabric API-0.57.0+1.18.2
Patchouli-1.18.2-71.1-Fabric
Roughly Enough Items-8.1.457
The Forge-1.2.0

**Comment by sussy-syrup** [comment]
This issue is fixed now and took a lot more work-around code than I would like to use. It should be fixed in the next release
