### ISSUE TITLE
[Bug] Weird render issue

### ISSUE THREAD

**Issue by Pirogiran** [sussy-syrup/smithees-foundry#31]
![image](https://user-images.githubusercontent.com/99805468/186698941-966d9a43-ec96-4c42-a236-73cf272b1c12.png)
Don't know if this is known issue, but i'm using last release (not beta).
Mods:
![image](https://user-images.githubusercontent.com/99805468/186699211-efe6d8ac-7845-4afe-9dba-d6ca82bc1fe4.png)

**Comment by sussy-syrup** [comment]
Sodium does not support fabric api rendering without indium. You can get it here:

https://www.curseforge.com/minecraft/mc-mods/indium

sodium also messes with animated textures so if fluids in the smeltery seem to not animate, disabling that in the config should solve the issue.
