### ISSUE TITLE
Make creating and upgrading tools more survival friendly

### ISSUE THREAD

**Issue by Steveplays28** [sussy-syrup/smithees-foundry#34]
It'd be nice if Smithee's Foundry could be used as a full replacement for all normal vanilla/modded tools, like you could in Tinker's Construct 1.7.10.
TC made every normal tool have 1 durability, so you could only use them for crafting. This would also incentivize creating Smithee's Foundry tools more.

The blocks/tools (chisel, part bench, repair anvil) used to create/upgrade Smithee's Foundry tools are also not obtainable in early game, since they require iron and stone.
It'd be nice if the recipes only required wood, so you can get started easily. Or at least the crude chisel, so you can start mining stone and iron for the repair anvil and forge.

**Comment by sussy-syrup** [comment]
Thank you for your request. Unfortunately I have too little free time to work on this mod at the moment. I do have plans for making something similar to what you have requested when I find that time

**Comment by Steveplays28** [comment]
No worries! Mod is looking super cool and promising already. Take your time.

**Comment by sussy-syrup** [comment]
Upgrading tools will be reworked but for now I regard this as complete. The current changes will be incorporated in the next release which will be very soon

**Comment by Steveplays28** [comment]
nice!
