### ISSUE TITLE
Smithee's Foundry not working on Dedicated Server

### ISSUE THREAD

**Issue by Adhan-Razzaque** [sussy-syrup/smithees-foundry#8]
I'm currently trying to run a dedicated server with Smithee's Foundry and it crashes on startup.

The server I ran is on Minecraft 1.18.2, Fabric 0.14.8, and contains Fabric API 0.57.0, Patchouli 71.1, and Smithee's Foundry 1.3.0.1.

Here's the log for reference: [latest.log](https://github.com/sussy-syrup/smithees-foundry/files/9128612/latest.log)

Any insight on what this is?

**Comment by sussy-syrup** [comment]
I have accidentally left client side only code in the main loading loop. I will fix it

**Comment by sussy-syrup** [comment]
methods that were not called and marked for client were for some reason not handled correctly. Moving them to separate classes fixes the issue. Now to sort the api and actually leave api methods only in it...
