### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Gamerbolts** [sussy-syrup/smithees-foundry#9]
Hello! I am constructing a rather large modpack and have tons of mods that add materials. Will you be adding support to make tools out of other mods materials like Tinkers at some point? This is awesome btw I was really hoping for Tinkers in Fabric :) Thank you for this!

**Comment by Gamerbolts** [comment]
Yes that does answer my question. Thanks so much!

**Comment by sussy-syrup** [comment]
I have discontinued this mod mainly because I don't reckon I would have enough time to work on it anymore. There is a tinker's construct port in the works by someone else
